## This workflow is executed automatically in every branch push.
##
## Project: Frontend
## Repository: https://github.com/shillingdotfun/frontend.git
## Version: 0.0.1
## Aim: Build the project.

name: Check Build

# This workflow is triggered manually
on:
  push:

env:
  NODE_VERSION: 24

defaults:
  run:
    shell: bash

jobs:
  build:

    name: Check build process
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Clone the repository
        uses: actions/checkout@v5

      # https://github.com/actions/setup-node
      - name: Use Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Generate env file
        run: |
          cp .env.example .env

      - name: Install the project dependencies
        run: npm install

      - name: Build the project
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build

      # https://github.com/slackapi/slack-github-action
      - name: Send failure notification
        if: failure()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Test Build process for the frontend - Status: success"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: ":rotating_light: :rotating_light: *Test Build process for the frontend failed!* :rotating_light: :rotating_light:"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Repository:* ${{ github.repository }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Branch:* ${{ github.ref }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Commit:* ${{ github.sha }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Workflow:* ${{ github.workflow }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Run ID:* ${{ github.run_id }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*User:* ${{ github.actor }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Run ID URL:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
